# @package _global_

# default evaluate setup
# other evaluate configs can inherit from this one

# overwrite task name so debugging logs are stored in separate folder
task_name: "evaluate"

# disable callbacks and loggers during debugging
callbacks: null

train: False

test: False 

mode: "evaluate"
evaluate: true



# in evaluate mode, must give these params!!!!!
# evaluate_savedir: "/home/panpan/rl4co/logs/train/runs/tsp50/am-tsp50/2023-12-29_09-28-33"
# ckpt_path: "/home/panpan/rl4co/logs/train/runs/tsp50/am-tsp50/2023-12-29_09-28-33/rl4co/mql00v5r/checkpoints/epoch=2-step=3.ckpt"
evaluate_savedir: "/home/panpan/rl4co/logs/train_rarl/runs/opsptw20/am-opsptw20/2024-04-17_08-42-21"
eval_withadv: true
ckpt_rarl_path: "/home/panpan/rl4co/logs/train_rarl/runs/opsptw20/am-opsptw20/2024-04-17_08-42-21/rl4co-adv/4husiy07/checkpoints/epoch=99-step=625000.ckpt"
#"/home/panpan/rl4co/logs/train_rarl/runs/svrp20/am-svrp20/2024-03-01_17-17-27/rl4co-adv/4mbljtbu/checkpoints/epoch=99-step=305000.ckpt"
eval_rarl: true   # 是否测评rarl算法训练出来的prog
another: false
another_rarl_prog_path: "/home/panpan/rl4co/logs/train_rarl/runs/svrp20/am-svrp20/2024-03-12_14-14-24/rl4co-adv/049hb7g5/checkpoints/epoch=99-step=625000.ckpt"

eval_rl: true   # 是否测评普通rl算法训练出来的prog
ckpt_prog_path: "/home/panpan/rl4co/logs/train/runs/opsptw20/am-opsptw20/2024-04-17_13-38-13/rl4co/fr7wf3r2/checkpoints/epoch=99-step=125000.ckpt"
evaluate_loc: "${evaluate_savedir}"
evaluate_method: "greedy"   # ["greedy", "sampling", "greedy_multistart", "augment_dihedral_8", "augment", "greedy_multistart_augment_dihedral_8", "greedy_multistart_augment"]

